## NON GRADED CHALLENGE 5

Name    : Engelberta Vania
Batch   : Data Science Batch 9

In [7]:
import numpy as np

In [3]:
from numpy import array

## NO. 1
Buatlah Tensor di bawah ini dengan Python

In [5]:
Tensor=array([[[23,50],[7,12]],
            [[57,67],[99,43]],
            [[75,21],[57,12]],
            [[87,26],[8,84]]])
print(Tensor)

[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [ 8 84]]]


## NO. 2
Lakukan perkalian terhadap matrix berikut

In [10]:
A=np.array([[23,50,19],
            [7,12,109],
            [57,67,98]])
B=np.array([[17,],
            [22],
            [19]])

In [11]:
A*B

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

## NO. 3
Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini

In [12]:
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [13]:
from numpy.linalg import det

In [14]:
det(A)

131344.0000000002

In [15]:
print(A)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]


In [17]:
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])