## Non Graded Challenge

Name    : Engelberta Vania
Batch   : Data Science Batch 9

In [1]:
# Import package yang digunakan yaitu numpy
import numpy as np

In [6]:
#  Buatlah vektor di bawah ini dengan Python:
A=np.array([17,22,19])

In [7]:
# Membuat vektor 
B=np.array([10,20,11])
C=np.array([5,12,9])

In [8]:
# Hitunglah:A+B
A+B

array([27, 42, 30])

In [9]:
# Hitunglah:B-C
B-C

array([5, 8, 2])

In [10]:
# Hitunglah:A dot C
A.dot(C)

520

In [18]:
# Hitunglah:A x B
A*B

array([170, 440, 209])

In [12]:
# itunglah:norm A
np.linalg.norm(A)

33.67491648096547

## Hitunglah: Sudut antara vektor A dan B

In [14]:
cos_theta=A@B/(np.linalg.norm(A)*np.linalg.norm(B))
print(cos_theta)

0.9759590023331435


In [15]:
rad=np.arccos(cos_theta)
rad

0.21971776576153962

In [17]:
degree=np.degrees(rad)
degree

12.588900662180242